LogAppender for java platform/system logger
zio/zio-logging pull request #493
Opened 2022-08-18 20:29 UTC by justcoon

similar to `slf4j` backend implementation

default behavior:
- all annotations are placed at the beginning of log message
- cause - LogAppender.appendCause - as throwable, Cause transformed into FiberFailure
- logger name extracted from `Trace`, added `JPL.loggerName` zio LogAnnotation for custom logger name
- updated documentation and examples

open questions:
- `slf4j` and this `jpl` implementation got custom logger name aspect, should not we do common one?
-  by default both are  appending all LogAnnotations-s, including logger name annotation, there is question if this annotation should not be excluded in default setup, because if logger name is extracted from Trace, there is not logger name annotation

related to  #322 (from this ticket it is not clear if this was requirement for backend implementation like slf4j or it should be something similar to slf4j-bridge)

2022-08-18 20:34 UTC, justcoon commented
NOTE: 
CI setup needs to be updated, as java platform/system logger was introduced at [`JDK9`](https://openjdk.org/jeps/264)

2022-09-10 14:41 UTC, jdegoes commented on jpl/src/main/scala/zio/logging/backend/JPL.scala
> +  def getLoggerName(default: String = "zio-jpl-logger"): Trace => String =
This should be hidden / made private.

2022-09-10 14:42 UTC, jdegoes commented on jpl/src/main/scala/zio/logging/backend/JPL.scala
> +  def jpl: ZLayer[Any, Nothing, Unit] =
This can be a `val`.

2022-09-10 14:42 UTC, jdegoes requested changes
Just minor tweaks, and then good to merge!

2022-09-10 15:37 UTC, justcoon commented
@jdegoes - comments solved

2022-09-11 10:34 UTC, jdegoes approved these changes

2022-09-11 10:34 UTC, merged